/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Hp
 */
public class FrmPinturas extends javax.swing.JFrame {

    String[] catalogoColores = {
        "Blanco Puro", "Blanco Humo", "Marfil / Hueso", "Crema Clásico", "Beige Arena",
        "Gris Perla", "Gris Cemento", "Marrón Chocolate", "Negro Absoluto",
        "Azul Cielo", "Azul Rey", "Turquesa Caribe", "Verde Limón", "Verde Hoja",
        "Rosa Bebé", "Rosa Fucsia", "Rojo Bandera", "Naranja Ladrillo", "Lila Lavanda", "Violeta Intenso"
    };

    String[] tintes = {"Base Blanca", "Tinte Rojo", "Tinte Azul", "Tinte Amarillo", "Tinte Negro"};

    double[][] matrizRecetas = {
        // BLANCOS
        {1.00, 0.00, 0.00, 0.00, 0.00}, // Blanco Puro
        {0.95, 0.00, 0.00, 0.04, 0.01}, // Blanco Humo
        {0.90, 0.02, 0.00, 0.08, 0.00}, // Marfil
        {0.85, 0.05, 0.00, 0.10, 0.00}, // Crema
        {0.90, 0.02, 0.02, 0.06, 0.00}, // Beige
        // GRISES
        {0.80, 0.00, 0.00, 0.00, 0.20}, // Gris Perla
        {0.50, 0.00, 0.00, 0.00, 0.50}, // Gris Cemento
        {0.10, 0.30, 0.10, 0.40, 0.10}, // Marrón
        {0.00, 0.00, 0.00, 0.00, 1.00}, // Negro
        // AZULES/VERDES
        {0.70, 0.00, 0.30, 0.00, 0.00}, // Azul Cielo
        {0.10, 0.10, 0.80, 0.00, 0.00}, // Azul Rey
        {0.50, 0.00, 0.40, 0.10, 0.00}, // Turquesa
        {0.60, 0.00, 0.05, 0.35, 0.00}, // Verde Limón
        {0.20, 0.00, 0.40, 0.40, 0.00}, // Verde Hoja
        // ROJOS/VIOLETAS
        {0.80, 0.20, 0.00, 0.00, 0.00}, // Rosa Bebé
        {0.50, 0.50, 0.00, 0.00, 0.00}, // Fucsia
        {0.00, 0.90, 0.00, 0.10, 0.00}, // Rojo Bandera
        {0.10, 0.50, 0.00, 0.40, 0.00}, // Naranja Ladrillo
        {0.60, 0.20, 0.20, 0.00, 0.00}, // Lila
        {0.20, 0.40, 0.40, 0.00, 0.00}  // Violeta
    };
    public FrmPinturas() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        cboColores.removeAllItems();
        for (String color : catalogoColores) {
            cboColores.addItem(color);
        }

        txtReceta.setFont(new java.awt.Font("Monospaced", java.awt.Font.BOLD, 14));
        
        txtReceta.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboColores = new javax.swing.JComboBox<>();
        btnMezclar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReceta = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 550));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Seleccione su color :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 80, 200, 30);

        cboColores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboColores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboColoresActionPerformed(evt);
            }
        });
        getContentPane().add(cboColores);
        cboColores.setBounds(190, 80, 140, 30);

        btnMezclar.setText("GENERAR RECETA");
        btnMezclar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMezclarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMezclar);
        btnMezclar.setBounds(40, 430, 130, 30);

        txtReceta.setColumns(20);
        txtReceta.setRows(5);
        jScrollPane1.setViewportView(txtReceta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 110, 290, 300);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("CATÁLOGO TINTOMÉTRICO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 30, 230, 40);

        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(220, 430, 110, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboColoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboColoresActionPerformed

    private void btnMezclarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMezclarActionPerformed
       // 1. Obtener índice seleccionado
    int fila = cboColores.getSelectedIndex();
    
    StringBuilder ticket = new StringBuilder();
    
    // CABECERA
    ticket.append("================================\n");
    ticket.append("      CENTRO DE MATIZADO        \n");
    ticket.append("================================\n");
    ticket.append("PRODUCTO: ").append(catalogoColores[fila].toUpperCase()).append("\n");
    ticket.append("VOLUMEN : 1 Galón (4000 ml)\n");
    ticket.append("--------------------------------\n");
    ticket.append("       FÓRMULA EXACTA           \n");
    ticket.append("--------------------------------\n");
    
    for (int col = 0; col < 5; col++) {
        
        double porcentaje = matrizRecetas[fila][col];
        
        if (porcentaje > 0) {
            double ml = porcentaje * 4000;
            int pct = (int)(porcentaje * 100);
            
            String linea = String.format("%-15s : %3d%% (%4.0f ml)", 
                                         tintes[col], pct, ml);       
            ticket.append(linea).append("\n");
        }
    } 
    ticket.append("\n================================\n");
    ticket.append(" Agitar antes de entregar.\n");
    ticket.append(" Válido por 24 horas.\n");
    ticket.append("================================");

    txtReceta.setText(ticket.toString());

    }//GEN-LAST:event_btnMezclarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // 1. Crear y mostrar el Menú Principal otra vez
    MenuPrincipal menu = new MenuPrincipal();
    menu.setVisible(true);
    
    // 2. Cerrar esta ventana de Pinturas
    this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPinturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPinturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPinturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPinturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPinturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMezclar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cboColores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtReceta;
    // End of variables declaration//GEN-END:variables
}
