/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import datos.Repositorio;
import modelo.Producto;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Hp
 */
public class VentanaVentas extends javax.swing.JFrame {

    // 1. VARIABLES GLOBALES
    Repositorio repo = new Repositorio();      // Para leer el archivo
    ArrayList<Producto> listaProductos;        // La lista de materiales
    DefaultTableModel modeloTabla;             // Para controlar la tabla
    double totalPagar = 0.0;                   // Acumulador de dinero

    // 2. CONSTRUCTOR (Lo que se ejecuta al abrir la ventana)
    public VentanaVentas() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Caja de Ventas - Todo Construcción");
        
        // Configurar la tabla
        modeloTabla = (DefaultTableModel) tblCarrito.getModel();
        
        cargarComboProductos(); 
        mostrarFecha(); 
    }
    
    // Método auxiliar para llenar la cajita con los nombres del archivo
    private void cargarComboProductos() {
        listaProductos = repo.cargarProductos(); // Leemos el TXT
        cboProductos.removeAllItems(); // Limpiamos por si acaso
        
        for (Producto p : listaProductos) {
            cboProductos.addItem(p.getNombre());
        }
        
    }
     // Muestra la fecha y hora actual en la etiqueta
     private void mostrarFecha() {
     // 1. Capturamos el momento exacto (Fecha + Hora)
     LocalDateTime ahora = LocalDateTime.now();

    // 2. Le damos formato bonito (Día/Mes/Año Hora:Minuto)
    DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

    // 3. Lo ponemos en la etiqueta
    lblFecha.setText("FECHA: " + ahora.format(formato));
    
}
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        cboProductos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarrito = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        btnVender = new javax.swing.JButton();
        lblFecha = new javax.swing.JLabel();
        ButonRegresa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblSubtotal = new javax.swing.JLabel();
        lblIGV = new javax.swing.JLabel();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Producto:");

        jLabel2.setText("Cantidad:");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        tblCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Precio", "Cantidad", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblCarrito);

        lblTotal.setText("TOTAL A PAGAR: S/ 0.00");
        lblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnVender.setText("GENERAR VENTA");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        lblFecha.setText("00/00/0000");

        ButonRegresa.setText("REGRESAR");
        ButonRegresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButonRegresaActionPerformed(evt);
            }
        });

        jButton1.setText("ELIMINAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblSubtotal.setText("SUBTOTAL: S/ 0.00");

        lblIGV.setText("IGV(18%): S/ 0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAgregar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cboProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(ButonRegresa)
                        .addGap(40, 40, 40)
                        .addComponent(jButton1)))
                .addContainerGap(157, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTotal)
                            .addComponent(btnVender)
                            .addComponent(lblFecha)
                            .addComponent(lblSubtotal)
                            .addComponent(lblIGV))
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIGV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtotal)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnVender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButonRegresa)
                    .addComponent(jButton1))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
                                      
        // 1. VERIFICAR QUE HAYA UN PRODUCTO SELECCIONADO EN EL COMBO
        if (cboProductos.getSelectedIndex() == -1) {
             javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un producto");
             return;
        }

        // 2. VALIDACIÓN DE ERRORES (El Airbag 🛡️)
        int cantidad = 0;
        
        try {
            // Intentamos convertir el texto a número
            cantidad = Integer.parseInt(txtCantidad.getText());
            
            // VALIDACIÓN 1: ¿Es negativo o cero?
            if (cantidad <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                        "¡La cantidad debe ser mayor a 0!", 
                        "Error de Cantidad", 
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                txtCantidad.setText(""); // Limpiamos la caja
                txtCantidad.requestFocus(); // Ponemos el cursor ahí
                return; // Detenemos todo aquí
            }
            
        } catch (NumberFormatException e) {
            // VALIDACIÓN 2: ¿Escribió letras o símbolos?
            // Si falla la conversión (ej: "hola"), el programa salta directo aquí
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "¡Error! Ingrese solo números enteros.\nNo se permiten letras ni símbolos.", 
                    "Error de Formato", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            txtCantidad.setText("");
            txtCantidad.requestFocus();
            return;
        }

        // --- SI LLEGAMOS AQUÍ, EL NÚMERO ES VÁLIDO ---

        // 3. Obtener datos del producto seleccionado
        int indice = cboProductos.getSelectedIndex();
        modelo.Producto productoSeleccionado = listaProductos.get(indice);
        
        // 4. Validar Stock
        if (cantidad > productoSeleccionado.getStock()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "¡Stock insuficiente!\nSolo quedan: " + productoSeleccionado.getStock(),
                    "Advertencia",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 5. Calcular Subtotal y Agregar a Tabla
        double precio = productoSeleccionado.getPrecio();
        double subtotal = precio * cantidad;
        
        Object[] fila = new Object[4];
        fila[0] = productoSeleccionado.getNombre();
        fila[1] = precio;
        fila[2] = cantidad;
        fila[3] = subtotal;
        modeloTabla.addRow(fila);
        
        // 6. Actualizar Total y restar stock temporalmente
        totalPagar += subtotal;
        lblTotal.setText("TOTAL A PAGAR: S/ " + totalPagar);
        
        productoSeleccionado.setStock(productoSeleccionado.getStock() - cantidad);
        txtCantidad.setText(""); // Limpiar para el siguiente
        txtCantidad.requestFocus();
        
        
        
        double baseImponible = totalPagar / 1.18;
        double igv = totalPagar - baseImponible;
        
        // 2. ACTUALIZAR LAS 3 ETIQUETAS POR SEPARADO
        // Usamos String.format para que siempre salgan 2 decimales
        
        lblSubtotal.setText(String.format("Subtotal: S/ %.2f", baseImponible));
        
        lblIGV.setText(String.format("IGV (18%%): S/ %.2f", igv));
        
        lblTotal.setText(String.format("TOTAL A PAGAR: S/ %.2f", totalPagar));
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
           // 1. VERIFICAR CARRITO VACÍO
        if (modeloTabla.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "El carrito está vacío");
            return;
        }

        // ---------------------------------------------------------
        // 2. SELECCIONAR MÉTODO DE PAGO (SIMULACIÓN)
        // ---------------------------------------------------------
        String[] opciones = {"Efectivo", "Yape / QR", "Tarjeta Visa"};
        
        int seleccion = JOptionPane.showOptionDialog(
                this,
                "Seleccione método de pago:",
                "Procesando Pago",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones,
                opciones[0]
        );

        // Si el usuario cierra la ventana sin elegir, cancelamos la venta
        if (seleccion == -1) {
            return; 
        }

        String metodoPago = "";

        // LÓGICA SEGÚN LA OPCIÓN ELEGIDA
        switch (seleccion) {
            case 0: // Efectivo
                metodoPago = "EFECTIVO";
                break;
               case 1: // Yape / QR
                metodoPago = "YAPE / PLIN";
                
                // 1. Cargar la imagen original (Grande)
                javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon("yape.png");
                
                // 2. REDIMENSIONAR (Aquí está el truco)
                // Obtenemos la imagen, le damos tamaño 200x200 y usamos suavizado (SCALE_SMOOTH)
                java.awt.Image imagen = iconoOriginal.getImage();
                java.awt.Image imagenRedimensionada = imagen.getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH);
                
                // 3. Convertimos de nuevo a Icono
                javax.swing.ImageIcon iconoMini = new javax.swing.ImageIcon(imagenRedimensionada);
                
                // 4. Mostrar el QR pequeño
                JOptionPane.showMessageDialog(this, 
                        "Muestre este QR al cliente para pagar: S/ " + totalPagar, 
                        "Escanee para pagar", 
                        JOptionPane.PLAIN_MESSAGE, 
                        iconoMini); // <--- Pasamos el icono ya reducido
                break; 
            
                
            case 2: // Tarjeta
                metodoPago = "TARJETA VISA";
                // Simulación de procesando...
                JOptionPane.showMessageDialog(this, "Conectando con POS Visa... \n¡Transacción Aprobada!");
                break;
        }
        
        
// CÁLCULOS FINALES
    double baseImponible = totalPagar / 1.18;
    double igv = totalPagar - baseImponible;

    // ARMADO DE LA BOLETA (Usando StringBuilder para orden)
    StringBuilder boleta = new StringBuilder();
    boleta.append("============== CONTRU - MAX S.A.C. ==============\n");
    boleta.append("              RUC: 20123456789\n");
    boleta.append("           BOLETA DE VENTA ELECTRÓNICA\n");
    boleta.append("=================================================\n");
    boleta.append("CANT.   DESCRIPCION             P.UNIT    IMPORTE\n");
    boleta.append("-------------------------------------------------\n");
    
    // Recorremos la tabla para listar productos
    for (int i = 0; i < modeloTabla.getRowCount(); i++) {
        String nombre = modeloTabla.getValueAt(i, 0).toString();
        String precio = modeloTabla.getValueAt(i, 1).toString();
        String cant = modeloTabla.getValueAt(i, 2).toString();
        String sub = modeloTabla.getValueAt(i, 3).toString(); // O la columna 4 si agregaste descuentos
        
        // Truco visual: Cortamos el nombre si es muy largo para que no descuadre
        if (nombre.length() > 15) nombre = nombre.substring(0, 15);
        
        // Formato de columnas (tabulaciones manuales)
        boleta.append(String.format("%-5s %-18s %-8s %-8s\n", cant, nombre, precio, sub));
    }
    
    boleta.append("-------------------------------------------------\n");
    boleta.append(String.format("OP. GRAVADA (SUBTOTAL) : S/ %.2f\n", baseImponible));
    boleta.append(String.format("I.G.V. (18%%)            : S/ %.2f\n", igv));
    boleta.append("-------------------------------------------------\n");
    boleta.append(String.format("IMPORTE TOTAL          : S/ %.2f\n", totalPagar));
    boleta.append("=================================================\n");
    boleta.append("         ¡Gracias por construir con nosotros!");

    // MOSTRAR Y GUARDAR
    javax.swing.JOptionPane.showMessageDialog(this, boleta.toString());
    
    // Aquí llamas a tu repositorio para guardar en el archivo...
    datos.Repositorio repo = new datos.Repositorio();
    repo.registrarVentaDiaria(boleta.toString());
    
    }//GEN-LAST:event_btnVenderActionPerformed

    private void ButonRegresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonRegresaActionPerformed
        // 1. Volver al Menú
        MenuPrincipal menu = new MenuPrincipal();

        menu.setVisible(true);

        // 2. Cerrar la caja de ventas

        this.dispose();
    }//GEN-LAST:event_ButonRegresaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // 1. VERIFICAR SI SELECCIONÓ UNA FILA
        int filaSeleccionada = tblCarrito.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Seleccione el producto que desea quitar de la tabla.",
                    "Error",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. RECUPERAR DATOS DE LA FILA ANTES DE BORRARLA
        // Necesitamos saber qué producto es y cuánto costaba para restar el total
        String nombre = modeloTabla.getValueAt(filaSeleccionada, 0).toString();
        int cantidad = Integer.parseInt(modeloTabla.getValueAt(filaSeleccionada, 2).toString());
        double subtotal = Double.parseDouble(modeloTabla.getValueAt(filaSeleccionada, 3).toString());
        
        // 3. DEVOLVER EL STOCK (Lógica Inversa)
        // Buscamos el producto en tu lista original y le sumamos lo que vamos a quitar
        for (modelo.Producto p : listaProductos) {
            if (p.getNombre().equals(nombre)) {
                // ¡Aquí ocurre la magia! Devolvemos el stock.
                p.setStock(p.getStock() + cantidad);
                break; 
            }
        }
        
        // 4. RESTAR AL TOTAL A PAGAR
        totalPagar = totalPagar - subtotal;
        lblTotal.setText("TOTAL A PAGAR: S/ " + totalPagar);
        
        // 5. BORRAR LA FILA DE LA TABLA
        modeloTabla.removeRow(filaSeleccionada);
        
        javax.swing.JOptionPane.showMessageDialog(this, "Producto retirado del carrito.");
        
        
        
        double baseImponible = totalPagar / 1.18;
        double igv = totalPagar - baseImponible;
        
        // 2. ACTUALIZAR LAS 3 ETIQUETAS POR SEPARADO
        // Usamos String.format para que siempre salgan 2 decimales
        
        lblSubtotal.setText(String.format("Subtotal: S/ %.2f", baseImponible));
        
        lblIGV.setText(String.format("IGV (18%%): S/ %.2f", igv));
        
        lblTotal.setText(String.format("TOTAL A PAGAR: S/ %.2f", totalPagar));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVentas().setVisible(true);
            }
        });
    }
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButonRegresa;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnVender;
    private javax.swing.JComboBox<String> cboProductos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIGV;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblCarrito;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
